### PR TITLE
CMake support

### PR DESCRIPTION
**Pull request by andrewfenn**
Hi,

I wanted to help out and I noticed that CMake support is on your list of things to do.

I've tested this branch so far ~~only on Linux~~ and am looking for more testers on other platforms to help test and fix issues.

The following isn't implemented in CMake:
- Windows Wii Remote support
- Build options for xbox platform (unless handled by OISPrereqs.h?)
- Build options for auto selecting iPhone (unless handled by OISPrereqs.h?)

The following has been changed:
- Removed project / make files
- Cleaned up the read me files and updated build instructions
- Added a license file
- Made library version configurable in just one place (top of CMakeLists.txt)

In the next few days/weeks I'll start testing this branch on OSX and eventually windows. Please feel free to take what you'd like if you're not sure about pulling in the whole branch, my aim was to just help you speed up getting CMake support added.

This branch was forked from your master branch.

Regards,
Andrew

Edit:
- Builds on Linux, Windows, and OSX. In the process of adding Travis CI integration.

### CODE REVIEW

**Comment by andrewfenn** [comment]
I got cmake generating xcode files no problem however I'm having all sorts of compiler errors due to the 1.4 code changes in the Mac specific files.

**Comment by andrewfenn** [comment]
There is a patch for fixing the OSX code issues with 1.4 available here: http://sourceforge.net/p/wgois/patches/35/

**Comment by andrewfenn** [comment]
So far so good. I imported David's patch and have OIS 1.4 building in OSX in both GCC and Clang via XCode. Having a small problem with linking the demos so I've set them to be disabled for now.

**Comment by TheOnlyJoey** [comment]
I think it would be a good idea to have the cmake compiling optional to the current makefiles, since they still are functional.
Maybe deprecate them over time if development asks for it, but lets not remove working things.

Could you reissue the pull request with the cmake in a seperate folder or something?

**Comment by andrewfenn** [comment]
Since this is a WIP it's probably better just to keep it in this pull request for now until we have all systems building at the very least.

As of right now:

* having issues linking OSX demos
* not tested on visual studio
* no work done on making wii remote on windows a cmake option
* having issues in mingw via mxe.cc

**Comment by samaursa** [comment]
I'm willing to test it on Windows with Visual Studio 2013/2015

**Comment by andrewfenn** [comment]
Stephen Kiazyk has helped me add windows support @samaursa if you'd like to still test it the branch is called "cmake" in my repository.

**Comment by TheOnlyJoey** [comment]
I am currently planning merging CMake to a separate branch for further testing.
Since CMake is also functional on BSD systems, I want some extensive testing for merging mainline.

**Comment by andrewfenn** [comment]
> Since CMake is also functional on BSD systems, I want some extensive testing for merging mainline.

Makes total sense. Haven't done any BSD testing yet.

In terms of the current branch conflicts it looks like you have moved the demo's source code to one directory up. I haven't resolved the conflicts on this yet as I've noticed that the code is broken in master, there is a bad merge on OISConsole.cpp that I've made an issue about (#17). 

Once master has been fixed up I'll merge master into this branch. :)

**Comment by andrewfenn** [comment]
FYI Windows builds are working fine, and I've hooked up automated windows builds with Appveyor. If you merge this you're going to need to change the Badge in the Readme file to your own repo

**Comment by andrewfenn** [comment]
Added Travis builds, and OSX demos now building and passing.

So far I have OSX, Linux, and Windows builds passing on both Appveyor, and Travis CI.

**Comment by andrewfenn** [comment]
Any updates on getting #17 fixed? It's blocking me from fixing the code conflicts.

**Comment by mob41** [comment]
@andrewfenn Are there still some major bugs must be fixed? I would like to use your ``CMakeLists.txt``` for building libraries.

**Comment by andrewfenn** [comment]
You should be able to use the branch in my fork. The code is the same just with cmake support.

**Pull request merged**
