### PR TITLE
OSX Non Exclusive Mouse

### PR DESCRIPTION
**Pull request by VisualEntertainmentAndTechnologies**
Adds support for non exclusive mouse mode for OSX.

Use Param “MacNonexclusiveMouse”

### CODE REVIEW

**Comment by Ybalrid** [comment]
@VisualEntertainmentAndTechnologies it looks like the changes in #12 and #13 are somewhat entangled. Also for some reason, you have changed the UNIX permission numbers on a bunch of files, and this PR as undesired side effect like moving copy (or move) constructors definitions around. 

I'm probably not going to both attempting to merge theses. code has diverged from the time you authored them and the PR aren't clean enough to salvage your fixes from them.

If you have the possibility, can you attempt to "forward port" (I'm inventing words here) the fixes on top of the current HEAD of the `master` branch? This would be great, but I understand you probably have better things to do... ;-)

I'm going to close #12 and close #13 for now, as I don't thing I can get anything useful out of them.

**Comment by VisualEntertainmentAndTechnologies** [comment]
Looks like some how I screwed up the PR's moving them from my SVN to this GIT. Sorry about that. 
I dont' recall why permissions were changed. Most likely it had something to do with getting the files to work with Codeblocks in OSX. Apply loves to make life difficult if you don't want to use their crap. 

Anyhoo, as for this PR, it's probably best to burry it and focus on getting Coca/64bit support on OSX. Carbon and 32-bit are EOL and will most likely be removed in the next OSX release.

**Comment by Ybalrid** [comment]
Oh. Well, current code is usung cocoa, but i woukd need hekp from somebody having a mac to validate if it actualky works. I am setting up a VM  wuth high sierra but it’s a reak hassle ;-)

--
Arthur Brainville (Ybalrid)
ESIEA 4A http://esiea.fr/

**Comment by VisualEntertainmentAndTechnologies** [comment]
Unfortunately my program is 32 bit and uses carbon. It will be some time before I attempt at porting it over to cocoa. So I won't be able to do any testing/feedback on this for several months.

**Comment by Ybalrid** [comment]
Okay, noted. I haven't dug through the code yet, I don't know if Carbon support is still present of it it was removed in the patch that implement Cocoa (I don't see a good reason they would have)

**Pull request closed without merging**
