### PR TITLE
improve keyboard

### PR DESCRIPTION
**Pull request by rpaciorek**
1. integrated pavlos256 'Improve LinuxKeyboard' (pull request #1) with current master
2. support NumLock and CapsLock as modifiers, with correct initial state (currently only for LinuxKeyboard)
3. improve KeyEvent to provide modifiers state and raw key code (need test for non Linux platform)

### CODE REVIEW

**Comment by akien-mga** [comment]
+1

**Comment by akien-mga** [comment]
Builds fine on Linux, I'm currently trying this PR + the master branch to see if it fixes issues I'm having with OIS 1.3.

**Comment by RebelliousX** [comment]
Just a question, does linux port support non buffered mode? That is using capture() the read status without events!

**Comment by Ybalrid** [comment]
There are a number of problems with how the linux keyboard code is put together. The Xlib isn't really helping the situation :wink; 
I will create a specific project within this repository to see what we can do about. I'm keeping the PR opened for the sake of discussion.

**Comment by Ybalrid** [comment]
@RebelliousX you can indeed call capture(), then use "isKeyDown()" to get the current status of a key on Linux

**Comment by Ybalrid** [comment]
@rpaciorek Hi, if you are still around, why do you want to expose ray key "numbers" exactly? The goal of the library is to be explicitely cross platform.

Otherwise, I will look into adding the capslock and numlock key states as "modifiers" for all OSes, this seems an useful feature.

Will close this PR for now, and create an issue for the caps/numlock state as modifiers. If you want to convince me about the usefulness of "raw key number", you can still comment here ;-)

**Comment by rpaciorek** [comment]
Hi,

I don't remember motivation for adding "raw key number" (2 years is a lot of time ...). Especially that KeySym is not very "raw". I don't use it in my project using OIS, too.

I think the main goal was to add capslock and numlock as modifier and sending modifier status in event (to ensure keycode+modifier consistency). This is used in my project ;-)

**Comment by Ybalrid** [comment]
Okay. 

The modifier thing will be integrated into OIS soon. We will keep track of that in Issue #34 ;-)

**Pull request closed without merging**
